sudo: required
services: 
    - docker

before_install:
    - docker build -t harone7/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true harone7/docker-react npm run test -- --coverage